### ISSUE TITLE
fix:  log4j customizations not loading

### ISSUE THREAD

**Issue by moabu** [GluuFederation/docker-oxshibboleth#69]
Due to a possible issue in the upstream oxshibboleth package the custom log4j is no prefixing the files as needed. The only prefix shown is `oxshibboleth-`

**Comment by iromli** [comment]
After doing comparison with CE version, I found that the issue is caused by having 2 `logback.xml` files.

1. `/opt/gluu/jetty/idp/resources/logback.xml` (this is custom `logback.xml` generated by entrypoint)
2. `/opt/shibboleth-idp/conf/logback.xml`

Even when we have set `-Dlogback.configurationFile=resources/logback.xml` Java option, Shib seems still loading the default one, hence it got mixed/overlapping.

Workaround:

1. generate custom `logback.xml` and replace `/opt/shibboleth-idp/conf/logback.xml`
2. set `-Dlogback.configurationFile=/opt/shibboleth-idp/conf/logback.xml` explicitly
3. remove `/opt/gluu/jetty/idp/resources/logback.xml` (if any) to avoid conflict

Patches is available in b8f9db4bdcf4309e90f7a0b3bd34bf320b8ddfe3.
